services:
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node_exporter
    ports:
      - "9100:9100"
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_METRICS_ENABLED=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  mongo_db:
    image: mongo:7
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped
  app:
    build: .
    container_name: app_container
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo_db:27017/ecommerce
      - JWT_SECRET=3f44e4555f09ecfe79f5d4f7ad6f7f65ef30b2dad19147e90d36e79c8cd9978b53277ef2b404f17b716700abb5e1286e
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
    networks:
      - app-network


networks:
  app-network:
volumes:
  mongo-data:
  prometheus_data:
  grafana_data:
